repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.13  # <-- проверь актуальную версию здесь: https://github.com/charliermarsh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        args: ["--diff"]

